// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FaaaaClient is the client API for Faaaa service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FaaaaClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type faaaaClient struct {
	cc grpc.ClientConnInterface
}

func NewFaaaaClient(cc grpc.ClientConnInterface) FaaaaClient {
	return &faaaaClient{cc}
}

func (c *faaaaClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/aaa222.dddd.Faaaa/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaaaaServer is the server API for Faaaa service.
// All implementations must embed UnimplementedFaaaaServer
// for forward compatibility
type FaaaaServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedFaaaaServer()
}

// UnimplementedFaaaaServer must be embedded to have forward compatible implementations.
type UnimplementedFaaaaServer struct {
}

func (UnimplementedFaaaaServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedFaaaaServer) mustEmbedUnimplementedFaaaaServer() {}

// UnsafeFaaaaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaaaaServer will
// result in compilation errors.
type UnsafeFaaaaServer interface {
	mustEmbedUnimplementedFaaaaServer()
}

func RegisterFaaaaServer(s grpc.ServiceRegistrar, srv FaaaaServer) {
	s.RegisterService(&Faaaa_ServiceDesc, srv)
}

func _Faaaa_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaaaaServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aaa222.dddd.Faaaa/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaaaaServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Faaaa_ServiceDesc is the grpc.ServiceDesc for Faaaa service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Faaaa_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aaa222.dddd.Faaaa",
	HandlerType: (*FaaaaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Faaaa_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Faaaa.proto",
}
