// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package Aaaaa

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// Server1Client is the client API for Server1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Server1Client interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type server1Client struct {
	cc grpc.ClientConnInterface
}

func NewServer1Client(cc grpc.ClientConnInterface) Server1Client {
	return &server1Client{cc}
}

func (c *server1Client) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/abcd.Aaaaa.Server1/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server1Server is the server API for Server1 service.
// All implementations must embed UnimplementedServer1Server
// for forward compatibility
type Server1Server interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedServer1Server()
}

// UnimplementedServer1Server must be embedded to have forward compatible implementations.
type UnimplementedServer1Server struct {
}

func (UnimplementedServer1Server) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedServer1Server) mustEmbedUnimplementedServer1Server() {}

// UnsafeServer1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Server1Server will
// result in compilation errors.
type UnsafeServer1Server interface {
	mustEmbedUnimplementedServer1Server()
}

func RegisterServer1Server(s grpc.ServiceRegistrar, srv Server1Server) {
	s.RegisterService(&Server1_ServiceDesc, srv)
}

func _Server1_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Server1Server).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abcd.Aaaaa.Server1/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Server1Server).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Server1_ServiceDesc is the grpc.ServiceDesc for Server1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Server1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "abcd.Aaaaa.Server1",
	HandlerType: (*Server1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Server1_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Server1.proto",
}
