// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HhhhhClient is the client API for Hhhhh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HhhhhClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type hhhhhClient struct {
	cc grpc.ClientConnInterface
}

func NewHhhhhClient(cc grpc.ClientConnInterface) HhhhhClient {
	return &hhhhhClient{cc}
}

func (c *hhhhhClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/Aaaaa.Ggggg.Hhhhh/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HhhhhServer is the server API for Hhhhh service.
// All implementations must embed UnimplementedHhhhhServer
// for forward compatibility
type HhhhhServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedHhhhhServer()
}

// UnimplementedHhhhhServer must be embedded to have forward compatible implementations.
type UnimplementedHhhhhServer struct {
}

func (UnimplementedHhhhhServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedHhhhhServer) mustEmbedUnimplementedHhhhhServer() {}

// UnsafeHhhhhServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HhhhhServer will
// result in compilation errors.
type UnsafeHhhhhServer interface {
	mustEmbedUnimplementedHhhhhServer()
}

func RegisterHhhhhServer(s grpc.ServiceRegistrar, srv HhhhhServer) {
	s.RegisterService(&Hhhhh_ServiceDesc, srv)
}

func _Hhhhh_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HhhhhServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Aaaaa.Ggggg.Hhhhh/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HhhhhServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Hhhhh_ServiceDesc is the grpc.ServiceDesc for Hhhhh service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Hhhhh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Aaaaa.Ggggg.Hhhhh",
	HandlerType: (*HhhhhServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Hhhhh_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Hhhhh.proto",
}
