// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package stubs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TttClient is the client API for Ttt service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TttClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type tttClient struct {
	cc grpc.ClientConnInterface
}

func NewTttClient(cc grpc.ClientConnInterface) TttClient {
	return &tttClient{cc}
}

func (c *tttClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/m11.pp11.Ttt/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TttServer is the server API for Ttt service.
// All implementations must embed UnimplementedTttServer
// for forward compatibility
type TttServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedTttServer()
}

// UnimplementedTttServer must be embedded to have forward compatible implementations.
type UnimplementedTttServer struct {
}

func (UnimplementedTttServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedTttServer) mustEmbedUnimplementedTttServer() {}

// UnsafeTttServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TttServer will
// result in compilation errors.
type UnsafeTttServer interface {
	mustEmbedUnimplementedTttServer()
}

func RegisterTttServer(s grpc.ServiceRegistrar, srv TttServer) {
	s.RegisterService(&Ttt_ServiceDesc, srv)
}

func _Ttt_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TttServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/m11.pp11.Ttt/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TttServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ttt_ServiceDesc is the grpc.ServiceDesc for Ttt service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ttt_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "m11.pp11.Ttt",
	HandlerType: (*TttServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Ttt_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Ttt.proto",
}
